### ISSUE TITLE
Dotted line link between nodes?

### ISSUE THREAD

**Issue by tanzid203** [dabeng/OrgChart#131]
How can we create dotted lines between nodes? I would love that.

For eg, something like this:

[ parent node ]------[ child node ]

**Comment by dabeng** [comment]
Hi @tanzid203 , maybe not the perfect solution, but you can try the following css code snippets:
```css
.orgchart tr.lines td.topLine { border-top-style: dashed; }
.orgchart tr.lines td.rightLine { border-right-style: dashed; }
.orgchart tr.lines td.leftLine { border-left-style: dashed; }
.orgchart tr.lines .downLine { background-color: transparent; width: 0; border: 1px dashed rgba(217, 83, 79, 0.8); }
```
