### ISSUE TITLE
Background without boxes

### ISSUE THREAD

**Issue by tanyona** [dabeng/OrgChart#160]
Is it possible to have the background not have the grid lines e.g. to have a plain white background

**Comment by dabeng** [comment]
Hi @tanyona , you just need the following code snippet:
```css
.orgchart {
    background: #fff;
}
```
