### ISSUE TITLE
Export on IE for vertical nodes not working properly

### ISSUE THREAD

**Issue by user165** [dabeng/OrgChart#206]
Hi @dabeng , I noticed that Export on IE for vertical nodes is not working properly. Some of the lines are not showing in the Export-ed file (see screenshot below). If you need more information, please let me know. Thanks.

<img width="136" alt="export ie vertical" src="https://cloud.githubusercontent.com/assets/26174119/25016162/818c2cd2-2044-11e7-9e8d-a85085984c5f.png">

**Comment by AWulkan** [comment]
I also have this problem. Hopefully I will find a solution for it, but it would be nice if someone else could help out if they have any ideas on how to solve it. :)

**Comment by AWulkan** [comment]
Ok, so here's some magic I came up with. It's not perfect, but it works for me. Simply add this into your own css:

```css
/* For the short vertical line */
.orgchart .verticalNodes > td {
    border: 0px solid rgba(255, 255, 255, 0);
}

/* For the horizontal line */
.orgchart .verticalNodes > td > ul > li:first-child::before {
    width: 49%;
}
```

From what I've gathered there's problems using `calc(50% - 2px)` in Internet Explorer, so I just switched it out for a static `49%`. It's good enough as a quick hack until a better solution is implemented. 

The 0px border that I added to a `td` element is pure magic, I don't know why it works. My idea was that the pseudo-element `::before` was messing things up, so I tried adding a border to the `td` element, and it worked. I made the line 0px and invisible because it serves no real purpose.

Anyway, do what you want with it, I'll leave it here so that other people might find it and improve upon it.
