### ISSUE TITLE
Modify node sizes without messing the display

### ISSUE THREAD

**Issue by dlarr** [dabeng/OrgChart#390]
Hello, 

I would like to modify the size of the nodes without modifying the rendered display of the chart;

I am using orgChart with angular2 project follwing this project model : https://github.com/Almo7aya/orgchart-with-angular

I want to display a L2R orgchart, but as soon as I modify node length, redering is all messed up:

At the moment I just tried to define SCSS vars and I tried to use them in the orgChart CSS:
```css
$org-chart-width: 130px;
$org-chart-height: 50px;
$org-chart-width-10 : calc(#{$org-chart-width} - 10px);
$org-chart-height-10 : calc(#{$org-chart-height} - 10px);
```

If I keep org-chart-width = 130px it's all working, but rendering is kinda bad because I can't see all the text

If I try to modify the width (say 200px) then, redering is all messed up : 
![image](https://user-images.githubusercontent.com/2865021/40903289-3350c7c2-67d7-11e8-856e-03b0d4f798df.png)

What can I do to enable a proper display regardless of the node size ?

**Comment by dlarr** [comment]
I modified these values : 

```css
$org-chart-width: 140px;
$org-chart-height: 70px;
$org-chart-width-10 : calc(#{$org-chart-width} - 10px);
$org-chart-height-10 : calc(#{$org-chart-height} - 10px);

.orgchart .node .content {
  box-sizing: border-box;
  width: 100%;
  // REMOVED : height: 20px;
  font-size: 11px;
  line-height: 18px;
  border: 1px solid rgba(217, 83, 79, 0.8);
  border-radius: 0 0 4px 4px;
  text-align: center;
  background-color: #fff;
  color: #333;
  // REMOVED : overflow: hidden;
  // REMOVED : text-overflow: ellipsis;
  // REMOVED : height: 20px;
  // REMOVED :  white-space: nowrap;
}

.orgchart.l2r .node, .orgchart.r2l .node {
  width: $org-chart-height;
  height: $org-chart-width-10;
}
```

Result is acceptable, although i'd rather have a dynamic height :)

![image](https://user-images.githubusercontent.com/2865021/41022233-3140af0e-6969-11e8-9fa5-ce934cad22e6.png)
